@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYWYyMmFkNi0xYTU3LTQ2NzYtODE4ZC0wMzg5MjU4YTEwODciLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiJiMDc3YjM2ZS1mMzc3LTRiMzEtYjRjMC00N2M1NzFhZTExOTQiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4MTM0NzAwfQ.yhizJMPNnUpnbu5--zlrWzXzj217ItBc9ktmCte27VY

### List categories

GET {{host}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
}
