@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MTcxNzhmMy0yMmI1LTQzNzgtOThlNy1lYzQwZTNjYmNmZmUiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiJhMTU3NDlhMy04NThiLTQ5YmEtYjc2My0yZjE5ZjU4MWZmNTMiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4MTMxNjkzfQ.5rs5GBouuTjDefGKrIE7plFt-BFJ-fA_CWyvJNnrG9Y

### List categories

GET {{host}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
}
