services:
  expense-manager-db:
    container_name: expense-manager-db
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: on-failure
  expense-manager-migrations:
    container_name: expense-manager-migrations
    build:
        context: .
        dockerfile: docker/migrations.dockerfile
    network_mode: "host"
    restart: on-failure
    depends_on:
      - expense-manager-db
  expense-manager-api:
    container_name: expense-manager-api
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - "5222:5222"
    network_mode: "host"
    restart: on-failure
    depends_on:
      - expense-manager-db
  expense-manager-client:
    container_name: expense-manager-client
    build:
      context: ./src/ExpenseManager.Presentation/Client
      dockerfile: docker/client.dockerfile
    ports:
      - "4173:4173"
    network_mode: "host"
    restart: on-failure
    depends_on:
      - expense-manager-api
