@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzlmMjkzZi1iY2Y3LTRmMDgtOThkOC1jNjk3Y2FkZTZkM2UiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiIyNmZhMzJjYy1jZmNhLTQxMWUtOGZlYS04OWVjZTFjNmI5YTAiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4ODMzMzc2fQ.7xUjPKQw-OXYfTkwZ2wGvONwciFUWq00TxbtIbAu_00

###

@categoryId1 = e15f41e7-4dde-4450-8782-e2db880b4c95

POST {{host}}/api/v1/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "test",
  "amount": 50.00,
   "type": "Expense",
  "date": 1718471967,
  "categoryIds": [
  ]
}
