@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYzQwMDk4Mi0yZTk1LTQ5MWQtOGIzOC1hNzE4ZjZhMzRlYTIiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiIxZTlhZGRiZC0yZGMwLTQyZWUtYmZmNC1mZWNjNmE5OTRjZWUiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4ODIxOTcwfQ.OHSWALXZ0bm2gHxf9PUg4aYAdgxAaI4PtjZobsX2hHM

###

@description = test
@categoryId1 = 20028217-eb12-4df1-a6bd-e975bbab6304

GET {{host}}/api/v1/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "filters": {
    "description": "{{description}}",
    "categoryIds": [
        "{{categoryId1}}"
    ],
    "dateRange": {
      "startDate": "2021-04-01",
      "endDate": "2021-04-30"
  }
  }
}
