@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzlmMjkzZi1iY2Y3LTRmMDgtOThkOC1jNjk3Y2FkZTZkM2UiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiIyNmZhMzJjYy1jZmNhLTQxMWUtOGZlYS04OWVjZTFjNmI5YTAiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4ODMzMzc2fQ.7xUjPKQw-OXYfTkwZ2wGvONwciFUWq00TxbtIbAu_00

###

@transactionId = 3323cb5c-2ea4-4ec7-8e78-7074dd66ba76

PUT {{host}}/api/v1/transactions/{{transactionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "Work",
  "amount": 45000,
   "type": "Income",
  "categoryIds": [
    "f52bce26-255d-4427-841b-e1d9a82206e9"
  ]
}
