@ExpenseManager.Api_HostAddress = http://localhost:5222

###

GET {{ExpenseManager.Api_HostAddress}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZGIwZTRkYi1kZTZmLTRiYmQtOGM1Ni02NGNhZmI0OWI2NzIiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiI0MTRhNGQ5ZC05OTJmLTQxOGYtOTI2Yi0wYzc2NTVlMGQ5Y2QiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE3NDE3MDU4fQ.XNWD75qM4QBp1glahjkvsjSeqCyNgAcGx6JxC0NqrZg
