@ExpenseManager.Api_HostAddress = http://localhost:5222

POST {{ExpenseManager.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "dominik@tichy.cz",
  "password": "password"
}

###