@ExpenseManager.Api_HostAddress = http://localhost:5222

### Register

POST {{ExpenseManager.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "Tichy",
  "email": "dominik@tichy.cz",
  "password": "password"
}

### Invalid last name

POST {{ExpenseManager.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "",
  "email": "dominik@tichy.cz",
  "password": "password"
}

### Invalid email

POST {{ExpenseManager.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "Tichy",
  "email": "dominik@",
  "password": "password"
}

