@host = http://localhost:5222

### Register

POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "Tichy",
  "email": "dominik@tichy.cz",
  "password": "Pa$$word1"
}
