@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWY3NDQxZi1kOGRlLTQ2OWEtODFjZS0yYTU0YjA1MmVjOGQiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiIxMDQzYWU2ZS1kY2IyLTQ1ZmMtOWFmYy1kNzA0NDU4YzMyMTgiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE3NzU3Mzg3fQ.0AAbmamfri1nGu7DJLzVCXCZD7_D0Z_I5vc21dTr_nA

@userId = a0e76427-5544-4ccf-abcf-9048dbfbcfe2

### Create transaction

POST {{host}}/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "Expense",
  "category": null,
  "description": "Today's lunch",
  "price": 159.00,
  "date": "2021-01-01T00:00:00Z"
}
