@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZjY3NWFmNS0wNjRjLTRkN2EtOWY0MS0wMmNkZWM1ZDRkOTkiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiJmZjZmNWY2MC0wODY2LTQzZjQtYmU2YS0wYThjYTk3MmVhODQiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE3NzEyNjI4fQ.ExpW4YFBKmwc1s2hfz4EB7yzZtLwC-JGSBgm9lLt2SE

@userId = a0e76427-5544-4ccf-abcf-9048dbfbcfe2

### Create transaction

POST {{host}}/users/{{userId}}/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "Expense",
  "category": "Food",
  "description": "Today's lunch",
  "price": 159.00,
  "date": "2021-01-01T00:00:00Z"
}
