@host = http://localhost:5222

### Login

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "dominik@tichy.cz",
  "password": "Pa$$word1"
}

### Invalid request

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "dominik@tichy.cz",
  "password": ""
}
