@host = http://localhost:5222

### Register

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Dominik",
  "lastName": "Tichy",
  "email": "dominik@tichy.cz",
  "password": "password"
}
