@ExpenseManager.Api_HostAddress = http://localhost:5222

### Correct credentials

POST {{ExpenseManager.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "dominik@tichy.cz",
  "password": "password"
}

### Ivalid credentials

POST {{ExpenseManager.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "dominik@tichy.cz",
  "password": ""
}

### Non existant email

POST {{ExpenseManager.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "something@not.exists",
  "password": ""
}

