@host = http://localhost:5222
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYWYyMmFkNi0xYTU3LTQ2NzYtODE4ZC0wMzg5MjU4YTEwODciLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiVGljaHkiLCJqdGkiOiI0MWMwNzNmOC03OTU2LTQzZTUtYjdlOC0zOWM2Yjg3YTcxZTUiLCJpc3MiOiJFeHBlbnNlTWFuYWdlciIsImF1ZCI6IkV4cGVuc2VNYW5hZ2VyIiwiZXhwIjoxNzE4MTM2OTkzfQ.MDlRPeSYrpBlVxXB3NVFJW29SerQ-braVTuPb84GYiU
@categoryId = 3506765c-9ff5-43e2-a83a-e1563a4b3dde

### Create transaction

POST {{host}}/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "Income",
  "categoryId": "{{categoryId}}",
  "description": "Today's lunch",
  "amount": 50.00,
  "date": "2024-06-07T15:02:43Z"
}
